name: Deploy

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install `pnpm` via Corepack
        run: corepack enable
      - name: Get `pnpm` Store Directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup `pnpm` Cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install All Dependencies
        run: pnpm install
      - name: Check Formatters
        run: pnpm run fmt
      - name: Compile Contract
        run: pnpm --filter=hardhat-resib run compile
      - name: Test Contract
        run: pnpm --filter=hardhat-resib test
      - name: Build Contract as Library
        run: pnpm --filter=hardhat-resib run build
      - name: Check HTML
        run: pnpm --filter=svelte-resib run lint:html
      - name: Inject Public Environment Variables
        working-directory: svelte
        run: echo 'PUBLIC_RESIB_DEPLOYMENT=0x4637e25808686165072C303d6215a9B2A7DCCDEA' > .env
      - name: Check CSS
        run: pnpm --filter=svelte-resib run lint:css
      - name: Synchronize SvelteKit
        run: pnpm --filter=svelte-resib run sync
      - name: Check JavaScript
        run: pnpm --filter=svelte-resib run lint:js
      - name: Check Svelte
        run: pnpm --filter=svelte-resib run lint:svelte
      - name: Build SvelteKit
        run: pnpm --filter=svelte-resib run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          projectName: resib
          directory: svelte/build
